### ISSUE TITLE
Is it possible for it to work on wayland?

### ISSUE THREAD

**Issue by hrqmonteiro** [luisbocanegra/kwin-panel-auto-hide#7]
Tested here and only works on X11

**Comment by luisbocanegra** [comment]
I am currently not using the script because is not yet in a state I would like to be. 

That said, just enabled it to see if maybe some recent update broke it, but is still working for me on Wayland (which I daily drive now). 

Can you run `journalctl -f | grep -E 'kwin_wayland|js'`, then disable/enable the sript and share the terminal output?

Note that I am busy with other things right now so it may take a while before I get back to fix/finish this project.
